version: '3'
services:
  mysql:
    image: mysql:5.7.16 
    restart: always
    container_name: mysql-02
    hostname: mysql-02
    environment:
      MYSQL_ROOT_PASSWORD: admin@1024
      TZ: Asia/Shanghai
    networks:
      - mysql-group-net
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$${MYSQL_ROOT_PASSWORD} -e 'select 1;' >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

      
networks:
  mysql-group-net:
    driver: bridge


